# Generated by Django 5.0.7 on 2024-11-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogexitpost_image_alter_blogrunpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogexitpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exit_a_business/'),
        ),
        migrations.AlterField(
            model_name='blogrunpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='run_a_business/'),
        ),
        migrations.AlterField(
            model_name='blogstartpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='start_a_business/'),
        ),
    ]
